spring.application.name=ST_DB
spring.application.name=GetInTouch

# PostgreSQL
spring.datasource.url=jdbc:postgresql://getintuch-stdb-7mulny:5432/PostgreSQL
spring.datasource.username=PostgreSQL
spring.datasource.password=PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port (important for Dokploy)
server.port=${PORT:8080}
