spring.application.name=ST_DB
#
#spring.datasource.url=jdbc:postgresql://dpg-d6p8181aae7s73bp3bng-a.oregon-postgres.render.com:5432/st_db_wgcy
#spring.datasource.username=st_db_wgcy_user
#spring.datasource.password=FTJmomYeEyTqKwbCENXdMWWl6blRE8ov
#
#
#
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect