spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 393420362459-ngac71299j9905ipq7pafd0pmo1uf502.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email