spring.application.name=ST_DB
#
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
##
spring.datasource.url=jdbc:postgresql://dpg-d6o42q7kijhs73edqd00-a.oregon-postgres.render.com:5432/st_db_zalp
spring.datasource.username=st_db_zalp_user
spring.datasource.password=8SJb8rJWyhJzNvaa2PG0TAXSa2OW7ZRB


spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect